config/routes.rb
Rails.application.routes.draw do

  get 'creatures/index'

  get '/' => 'home#index'

  resources :creatures

  get 'creatures/tag/:tag' => 'creatures#tag', as: :tagc

  resources :tags

  get '*path', to: "application#not_found"

end

app/models/creature.rb
class Creature < ActiveRecord::Base

  has_and_belongs_to_many :tags

  validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :desc, :presence => true

end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :creatures

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/concerns/home_controller.rb
class HomeController < ApplicationController

def index
    # @greeting = "good morning"
    # render plain: "hello"
end

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
    # @creature = Team.new()
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def create
    @creature = Creature.create(creature_params)
    @tags = Tag.all
    if @creature.errors.any?
      render 'new'
    else
      @creature.tags.clear
      tags = params[:creature][:tag_ids]
      tags.each do |tag_id|
        @creature.tags << Tag.find(tag_id) unless tag_id.blank?
      end
      flash[:success] = "Your creature has been added"
      redirect_to creatures_path
    end
  end

  def show
    @creature = Creature.find_by_id(params[:id])
    @tags = @creature.tags.map do |tag|
      tag.name
    end
    not_found unless @creature

    name = Creature.find(params[:id]).name
    list = flickr.photos.search :text => name, :sort => "relevance", :per_page => 20
    @results = list.map do |photo|
      FlickRaw.url_s(photo)
    end
    @response = RestClient.get 'http://www.reddit.com/search.json', {:params => {:q => name, :limit => 10}}
    @response_object = JSON.parse(@response)
    @reddit_posts = @response_object['data']['children']
  end

  def tag
    tag = Tag.find_by_name(params[:tag])
    @creatures = tag ? tag.creatures : []
  end

  def edit
    @creature = Creature.find_by_id(params[:id])
    @tags = Tag.all
  end

  def update
    @creature = Creature.find_by_id(params[:id])
    @creature.name = params[:creature][:name]
    @creature.desc = params[:creature][:desc]
    @creature.save

    @creature.tags.clear
    tags = params[:creature][:tag_ids]
    tags.each do |tag_id|
      @creature.tags << Tag.find(tag_id) unless tag_id.blank?
    end

    redirect_to creatures_path
  end

  def destroy
    @creature = Creature.find_by_id(params[:id])
    @creature.destroy
    redirect_to creatures_path
  end

  private

  def creature_params
    params.require(:creature).permit(:name, :desc)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def show
  end

  def create
    @tag = Tag.all
    @tag = Tag.create(tag_params)

    redirect_to tags_path
  end

  def edit
    @tag = Tag.find_by_name(params[:tag])
  end


  def destroy
    @tag = Tag.find(params[:id])
    # @tag.destroy

    if (@tag.creatures.length == 0)
      @tag.destroy
    else
      flash[:notice] = "You can't delete! " + @tag.creatures.length.to_s + " or more creatures have this tag."
    end

    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creatures/edit.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">

    <h1>Edit Creature</h1>

    <%= bootstrap_form_for :creature, url: creature_path(@creature), method: :patch do |f| %>

      <% if @creature.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@creature.errors.count, "error") %> prohibited
            this team from being saved:
          </h2>
          <ul>
            <% @creature.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.text_field :name, :placeholder => "Creature Name", :class => "form-control" %>
      <%= f.text_field :desc, :placeholder => "Creature Description", :class => "form-control" %>
      <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
      <%= f.submit :class => "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/creatures/index.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">

    <h1>Creatures</h1>

    <%= link_to 'Add New Creature', new_creature_path, :class=>'btn btn-primary'%>

    <p>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>

        <% @creatures.each do |creature| %>
          <tr>
            <td><%= creature.name %></td>
            <td><%= creature.desc %></td>
            <td><%= link_to 'Show creature', creature, :class=>'btn btn-primary'%></td>
            <td><%= link_to 'Delete Creature', creature, :class=>'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}%></td>
            <td><%= link_to 'Edit Creature', edit_creature_path(creature), :class=>'btn btn-primary'%></td>
          </tr>
        <% end %>

      </table>
    </p>

  </div>
</div>

app/views/creatures/new.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">

    <h2>Add New Creature</h2>
    <br>
    <div class="row">
      <%= bootstrap_form_for @creature do |f| %>
        <%= f.text_field :name, :placeholder => "Creature Name", :class => "form-control"%>
        <br>
        <%= f.text_field :desc, :placeholder => "Creature Description", :class => "form-control"%>
        <br>
        <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
        <%= f.submit :class => "btn btn-primary"%>
      <% end %>
    </div>

  </div>
</div>

app/views/creatures/show.html.erb
<div class="container">
  <div class="col-md-10">

    <h2><strong>Creature: <%= @creature.name %></strong><small> | <%= @creature.desc %></small></h2>

    <p>
      <% @creature.tags.each do |tag|%>
        <%= link_to tag.name, tagc_path(tag.name)%>
      <% end %>
    </p>

    <p><%= link_to '&larr; <b> back </b>'.html_safe, creatures_path %> </p>

    <br>

    <div class="img">
      <div class="row">
        <% @results.each do |photo|%>
          <% large = photo.gsub("_s","")%>
          <%= link_to image_tag(photo), large%>
        <% end %>
      </div>
    </div>

    <br>

    <div class="row">
    <h2>Reddit Posts About Creature</h2>
      <% @reddit_posts.each do |post|%>
        <li><%= link_to post['data']['title'], "http://www.reddit.com#{post['data']['permalink']}"%></li>
      <% end %>
    </div>


  </div>
</div>

app/views/creatures/tag.html.erb
<div class="container">
  <div class="col-md-8">
    <h1>Creatures with Tag: <small><%= params[:tag]%></small> </h1>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>
        <% @creatures.each do |creature| %>
          <tr>
            <td><%= creature.name %></td>
            <td><%= creature.desc %></td>
            <td><%= link_to 'Show creature', creature, :class=>'btn btn-primary'%></td>
            <td><%= link_to 'Delete Creature', creature, :class=>'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}%></td>
            <td><%= link_to 'Edit Creature', edit_creature_path(creature), :class=>'btn btn-primary'%></td>
          </tr>
        <% end %>
      </table>
  </div>
</div>

app/views/home/index.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <div class="creature_home_bkgrnd">
      <h1>Creatures Galore!</h1>
        <p>Come one, come all! Find all the creatures of our Bog Land. This is the place to create, find, add and edit the bog creatures.</p>
        <p>If you want to see <%= link_to 'all the Creatures', controller: 'creatures'%> in our Bog Land just click the link!</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreatureApp</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', '/' %></li>
            <li><%= link_to 'Creatures', creatures_path %></li>
            <li><%= link_to 'Tag List', tags_path %></li>
            <li><%= link_to 'New Creature', new_creature_path %></li>
            <li><%= link_to 'New Tag', new_tag_path %></li>
            <li><%= link_to '&larr; <b> back </b>'.html_safe, :back %></li>
                </ul>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

  </body>
</html>

app/views/partials/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key, message| %>
    <div class="alert alert- <%= key %>"><%= message %></d>
  <% end %>
<% end %>

app/views/tags/index.html.erb
<div class="container">
  <div class="col-md-6">
    <%= render partial: "partials/flash" %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th><h2>Creatures Tags List<h2>
             <p>
            <%= link_to "<button type='button' class='btn btn-primary'>Add Tag</button>".html_safe, new_tag_path %>
            </p>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
              <td><%= link_to tag.name, tagc_path(tag.name)%></td>
              <td><%= link_to 'Delete', tag, :class=>'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tags/new.html.erb
<div class="container">
  <div class="col-md-6">
    <h1>Add New Creatures Tag</h1>
      <p><%= link_to '&larr; <b> back </b>'.html_safe, creatures_path %> </p>
      <%= bootstrap_form_for @tag do |f| %>
        <%= f.text_field :name, :placeholder => "Create New Tag", :class => "form-control"%>
        <%= f.submit :class => "btn btn-primary" %>
      <% end %>
  </div>
</div>